export const Tasks = new Mongo.Collection('tasks')
export const Scripts = new Mongo.Collection('scripts')
export const Trails = new Mongo.Collection('trails')
export const Responses = new Mongo.Collection('responses')
export const Tracks = new Mongo.Collection('tracks')